apiVersion: v1
kind: Service
metadata:
  name: alertmanager
  namespace: kube-system
spec:
  ports:
    - name: http
      port: 9093
      targetPort: 9093
      protocol: TCP
  selector:
    k8s-app: alertmanager
  type: NodePort

