apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: kube-system
data:
  alertmanager.yml: |
    route:
      receiver: default-receiver
      group_interval: 5m
      group_wait: 10s
      repeat_interval: 4h
    receivers:
    - name: default-receiver
      webhook_configs:
      - url: http://your.receiver.address.com/
        send_resolved: true

