apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-exporter
  namespace: kube-system
  labels:
    k8s-app: node-exporter
spec:
  selector:
    matchLabels:
      k8s-app: node-exporter
  template:
    metadata:
      labels:
        k8s-app: node-exporter
    spec:
      tolerations:
        - key: node-role.kubernetes.io/master
        - key: node-role.kubernetes.io/not-ready
      priorityClassName: system-node-critical
      containers:
        - name: prometheus-node-exporter
          image: "registry.tongtech.com/library/prom/node-exporter:latest"
          imagePullPolicy: "IfNotPresent"
          args:
            - --path.rootfs=/host
          ports:
            - name: metrics
              containerPort: 9100
              hostPort: 9100
          volumeMounts:
            - name: host
              mountPath: /host
              readOnly:  true
          resources:
            requests:
              memory: 20Mi
      hostNetwork: true
      hostPID: true
      volumes:
        - name: host
          hostPath:
            path: /

