kind: Service
apiVersion: v1
metadata:
  name: prometheus
  namespace: kube-system
spec:
  ports:
    - name: http
      port: 9090
      protocol: TCP
      targetPort: 9090
  selector:
    k8s-app: prometheus
  type: NodePort

